package com.ssolab.auth.admin.audit;

public enum AdminAuditEvent {
    BOOTSTRAP_ADMIN_CLAIMED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_RESUMED,
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_MOVED,
    GROUP_DELETED,
    GROUP_ASSIGNED,
    GROUP_REMOVED,
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    ADMIN_REAUTH_SUCCESS,
    ADMIN_REAUTH_FAILED,
    ADMIN_EMAIL_REVEALED
}
