import { FormEvent, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { studioApi } from '../api'
import type { Artwork, Csrf, FrameType, SaleStatus } from '../types'

const empty = { title: '', description: '', year: '', material: '', widthCm: '', heightCm: '', price: '', saleStatus: 'NOT_FOR_SALE' as SaleStatus, frameType: 'NONE' as FrameType, published: false, featured: false }
export function ArtworkEditor({ csrf }: { csrf: Csrf }) {
  const { id } = useParams(); const navigate = useNavigate()
  const [form, setForm] = useState(empty); const [artwork, setArtwork] = useState<Artwork | null>(null)
  const [message, setMessage] = useState(''); const [confirmDelete, setConfirmDelete] = useState(false)
  useEffect(() => { if (id) void studioApi.artwork(id).then(item => { setArtwork(item); setForm({ title: item.title, description: item.description, year: item.year?.toString() ?? '', material: item.material ?? '', widthCm: item.widthCm.toString(), heightCm: item.heightCm.toString(), price: item.price?.toString() ?? '', saleStatus: item.saleStatus, frameType: item.frameType, published: item.published, featured: item.featured }) }).catch(() => setMessage('작품을 불러오지 못했습니다.')) }, [id])
  const set = (key: keyof typeof form, value: string | boolean) => setForm(previous => ({ ...previous, [key]: value }))
  const body = () => ({ ...form, year: form.year ? Number(form.year) : null, material: form.material || null, widthCm: Number(form.widthCm), heightCm: Number(form.heightCm), price: form.price ? Number(form.price) : null })
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(''); try { const saved = id ? await studioApi.update(csrf, id, body()) : await studioApi.create(csrf, body()); setArtwork(saved); setMessage('작품을 저장했습니다.'); if (!id) navigate(`/studio/artworks/${saved.id}`, { replace: true }) } catch (error) { setMessage(error instanceof Error ? error.message : '저장하지 못했습니다.') } }
  const upload = async (file?: File) => { if (!id || !file) return; try { await studioApi.upload(csrf, id, file); const refreshed = await studioApi.artwork(id); setArtwork(refreshed); setMessage('이미지를 업로드했습니다.') } catch { setMessage('이미지를 업로드하지 못했습니다.') } }
  return <section className="studio-page editor-page"><header className="studio-page-header"><div><Link to="/studio/artworks">← 작품 목록</Link><h1>{id ? '작품 수정' : '새 작품'}</h1></div></header>{message && <p className="inline-notice" role="status">{message}</p>}<form className="artwork-form" onSubmit={submit}><label>제목 *<input required maxLength={160} value={form.title} onChange={e => set('title', e.target.value)} /></label><label className="full">설명<textarea maxLength={5000} rows={8} value={form.description} onChange={e => set('description', e.target.value)} /></label><label>제작연도<input type="number" min="1000" max="9999" value={form.year} onChange={e => set('year', e.target.value)} /></label><label>재료<input maxLength={240} value={form.material} onChange={e => set('material', e.target.value)} /></label><label>가로(cm) *<input required type="number" min="0.01" step="0.01" value={form.widthCm} onChange={e => set('widthCm', e.target.value)} /></label><label>세로(cm) *<input required type="number" min="0.01" step="0.01" value={form.heightCm} onChange={e => set('heightCm', e.target.value)} /></label><label>가격<input type="number" min="0" step="1" value={form.price} onChange={e => set('price', e.target.value)} /></label><label>판매 상태<select value={form.saleStatus} onChange={e => set('saleStatus', e.target.value)}><option value="NOT_FOR_SALE">비매품</option><option value="AVAILABLE">판매 가능</option><option value="RESERVED">예약중</option><option value="SOLD">판매 완료</option></select></label><label>액자 타입<select value={form.frameType} onChange={e => set('frameType', e.target.value)}><option value="NONE">액자 없음</option><option value="MAT_BOARD">매트보드</option><option value="ACRYLIC_BOX">아크릴 관액자</option><option value="FLOATING_FRAME">띄움 액자</option></select></label><label className="check"><input type="checkbox" checked={form.featured} onChange={e => set('featured', e.target.checked)} /> 대표작</label><label className="check"><input type="checkbox" checked={form.published} disabled={!id || !artwork?.images.some(image => image.primary)} onChange={e => set('published', e.target.checked)} /> 공개</label><div className="full form-actions"><button className="primary-action" type="submit">저장</button>{id && <button className="danger-action" type="button" onClick={() => setConfirmDelete(true)}>작품 삭제</button>}</div></form>
  {id && <section className="image-manager"><h2>작품 이미지</h2><p>JPEG, PNG, WebP · 최대 12MB. 공개 화면은 대표 이미지 한 장을 사용합니다.</p><label className="upload-control">이미지 추가<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { void upload(e.target.files?.[0]) }} /></label><div className="image-list">{artwork?.images.map(image => <article key={image.id}><img src={image.thumbnailUrl.replace('/media/', '/studio/media/')} alt="업로드된 작품" /><span>{image.primary ? '대표 이미지' : '추가 이미지'}</span>{!image.primary && <button onClick={() => void studioApi.primary(csrf, id, image.id).then(() => studioApi.artwork(id)).then(setArtwork)}>대표로 지정</button>}<button onClick={() => void studioApi.removeImage(csrf, id, image.id).then(() => studioApi.artwork(id)).then(setArtwork)}>삭제</button></article>)}</div></section>}
  {confirmDelete && <div className="dialog-backdrop" role="presentation"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">작품을 삭제할까요?</h2><p>작품과 저장된 이미지가 함께 삭제됩니다.</p><div><button onClick={() => setConfirmDelete(false)}>취소</button><button className="danger-action" onClick={() => { if (id) void studioApi.remove(csrf, id).then(() => navigate('/studio/artworks')) }}>삭제</button></div></div></div>}
  </section>
}
